### ISSUE TITLE
Malfunctioning ChestLinks & Hopper Filters

### ISSUE THREAD

**Issue by Brittank88** [JamesPeters98/ChestsPlusPlus#1]
Hi JamesPeters98,

I run a small 1.14.4 paperspigot server (specifically git-Paper-195 implementing API version 1.14.4-R0.1-SNAPSHOT).

I have the following plugins:
![Plugins List](https://media.discordapp.net/attachments/219480949312847872/632550354327699466/unknown.png)

Some chestlinks work, others appear empty when opened from chests or commands and do not seem to be linked in any way.

Hopper filters work, and then without being touched stop working entirely.

I'm not sure what is going on, what conflicts could be present, etc., and would love your help in at least understanding what is going on.

Let me know if you need any more information, I'd be happy to provide!

Thanks for your time.

_P.S. Commands called incorrectly in any way cause_

> An internal error occurred while attempting to perform this command

_to be printed. I'm not sure if this is intentional, but it doesn't feel like it._

**Comment by Brittank88** [comment]
Not sure if I should expect a response, but either way I thought I might as well add that I managed to get it working, though it still seems somewhat inconsistent until it does eventually somehow work on its own. From observation it appears that chestlinks are a bit bugged when created via a sign on a double chest. The hopper filters are working now, but they were having issues before that, and nothing has changed since then so I'd call that inconsistent.

**Comment by JamesPeters98** [comment]
Hey @Brittank88 would you like to try the latest version of the plugin and see if you still have any issues? :) https://dev.bukkit.org/projects/chests-plus-plus

**Comment by JamesPeters98** [comment]
Closed as I think these issues are fixed in the 1.15 versions.
