### ISSUE TITLE
Limitations of the same linked chest

### ISSUE THREAD

**Issue by tmmjelde** [JamesPeters98/ChestsPlusPlus#12]
Seems like adding 64 of the same chest (typical dump chest on the top) causes flickering of all other chests and reduces performance of the game.
If there are items in the "dump" chest then the flickering stops.
If the config file contains "display_chestlink_armour_stands: false" then the issue stops.
![wtf](https://user-images.githubusercontent.com/20598976/88456618-41e64580-ce7f-11ea-8f5f-a2754948f8d1.gif)

**Comment by JamesPeters98** [comment]
Yep, very strange bug, currently looking into the reasons why it's occurring. Fix for now is only have 63 chests or less :D

**Comment by JamesPeters98** [comment]
This is fixed in the latest version v2.2.1
