### ISSUE TITLE
Item shorting

### ISSUE THREAD

**Issue by AbhikChatterjee94** [JamesPeters98/ChestsPlusPlus#14]
If you put two item frames on hopper one item as allowed one as blocked, when it comes to blocked item hopper stops and does not skip to next allowed item ! I set cobblestone as allow and stone as blocked !
![2](https://user-images.githubusercontent.com/64986691/88910102-915eb400-d279-11ea-823a-586029349a39.png)
![1](https://user-images.githubusercontent.com/64986691/88910104-93287780-d279-11ea-95de-763c7ae4167f.jpg)

**Comment by JamesPeters98** [comment]
This has been fixed in https://github.com/JamesPeters98/ChestsPlusPlus/commit/d1cc5d8289d5da289b8610e52f2cd0b615893c51
And will be part of the next release 👍
