### ISSUE TITLE
Hopper Filter only checks first slot of upper inventory

### ISSUE THREAD

**Issue by TetraTheta** [JamesPeters98/ChestsPlusPlus#16]
It seems Hopper Filter only checks first slot of upper inventory.  
I setup chest and hopper and hopper filter like this.  
![2020-08-13_21 02 05](https://user-images.githubusercontent.com/37061801/90132205-59db2600-dda8-11ea-8435-b7a10384b3a0.png)  
And If upper chest is like this, stone doesn't transfer to chest at bottom.  
![2020-08-13_21 02 13](https://user-images.githubusercontent.com/37061801/90132291-7f682f80-dda8-11ea-9215-46b93b6f62ed.png)  
If I place stone to first slot of upper chest, Hopper Filter works and only sends stone downwards.

It seems Hopper Filter should also check other slots of upper inventory so that even if targeted item exists in other slot other than first slot of inventory.  
I use plugin that does automatically sort chest so 'Just place stone at 1st slot' cannot be a solution.

**Comment by JamesPeters98** [comment]
I think this should be fixed in the next version, if you PM me on Discord I'll send you a beta version

**Comment by JamesPeters98** [comment]
Fixed in 2.3 afaik.
