### ISSUE TITLE
Download Link Broken

### ISSUE THREAD

**Issue by JasonGoemaat** [JamesPeters98/ChestsPlusPlus#2]
It seems the plugin download link on [spigotmc.org](https://www.spigotmc.org/resources/chests-chest-linking-hopper-filtering-remote-chests-menus.71355/) is hacked or something.  It opens a page with pop-ups that re-opens itself to fill the location history and doesn't seem to lead anywhere to download.

**Comment by JamesPeters98** [comment]
Hey! Please use the CurseForge page instead! https://dev.bukkit.org/projects/chests-plus-plus

**Comment by JamesPeters98** [comment]
The spigot page is now back up too https://www.spigotmc.org/resources/chests-chest-linking-hopper-filtering-remote-chests-menus.71355/
