### ISSUE TITLE
Missing recipe

### ISSUE THREAD

**Issue by Clashbestie** [JamesPeters98/ChestsPlusPlus#20]
The KelpBlock Recipe is not working.
Testet on 2.2.1 (1.16)
![Screenshot 2020-10-23 064228](https://user-images.githubusercontent.com/57112209/96957479-064d2d00-14fb-11eb-89d9-4df72d0243d5.png)

**Comment by JamesPeters98** [comment]
This will be fixed in version 2.3+
Join the discord if you'd like to test the Beta when it gets released!

**Comment by Clashbestie** [comment]
This seems to be a Bukkit bug and not your fault. I close tze issue.

**Comment by JamesPeters98** [comment]
> This seems to be a Bukkit bug and not your fault. I close tze issue. 

I have actually managed a work around and it will be fixed in 2.3!

**Comment by Clashbestie** [comment]
Nice. Cant wait for 2.3 and finally use Kelp as fully automated fuel.
