### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by BenisonQPS** [JamesPeters98/ChestsPlusPlus#21]
So far I've discovered Signs entering a Linked Chest disappear. I will add other items as I discover them. Other than that I find this Plugin SUPER Handy. Thanks

**Comment by JamesPeters98** [comment]
If you currently use a plugin that allows you to stack any items, e.g signs, up to 64 it'll break the plugin for now.
Let me know if that is what's causing the issue, if not post your plugin list.

**Comment by BenisonQPS** [comment]
I DO have simplistic running. Okay. I'm assuming that means there will be
other items as well that will disappear?

**Comment by BenisonQPS** [comment]
Simple Stack. Sorry...autocorrect....

**Comment by BenisonQPS** [comment]
After communication with SimpleStack Dev, problem is SOLVED! Thanks :-)

**Comment by JamesPeters98** [comment]
Oh nice! What was the issue, have they fixed it on their end then?

**Comment by BenisonQPS** [comment]
Yes, it was a little above my head though. lol.

**Comment by JamesPeters98** [comment]
Okay sweet! Glad your issue was fixed then!
