### ISSUE TITLE
Soundbug

### ISSUE THREAD

**Issue by GrobyZockt** [JamesPeters98/ChestsPlusPlus#3]
Hello, sorry for my bad English.

We have the problem when we use your Mod and f.e. CrazyCrate, and open the CC GUI we hear permantly a chest open-close sound. and whe have checked i have disable your mod then we hear nothing. can you please fix it. or ad a config file.

Thank You

**Comment by JamesPeters98** [comment]
Hey! sorry for the late reply, I think I've managed to fix this and will post an update shortly!

**Comment by JamesPeters98** [comment]
The fix should be going live on CurseForge soon! https://dev.bukkit.org/projects/chests-plus-plus
