### ISSUE TITLE
Hopper Filter only checks first slot (Paper, 1.16.3)

### ISSUE THREAD

**Issue by straubalexander** [JamesPeters98/ChestsPlusPlus#31]
I have seen the previous post with the same issue and it was marked as fixed in version 2.3. Unfortunately, I still have the same problem in 1.16.3. 
![2021-01-18_17 49 08](https://user-images.githubusercontent.com/77633685/104943143-947b6700-59b5-11eb-9f1c-8f108f290e81.png)
![2021-01-18_17 49 11](https://user-images.githubusercontent.com/77633685/104943154-96ddc100-59b5-11eb-97e9-3235804885a4.png)
![2021-01-18_17 49 13](https://user-images.githubusercontent.com/77633685/104943157-98a78480-59b5-11eb-94e4-7991fcc7b565.png)

How can I help further with the problem?

**Comment by JamesPeters98** [comment]
After a long while away from this issue, I think I might have a new solution.
