### ISSUE TITLE
Autocraft eats items that shouldn't be "eaten"

### ISSUE THREAD

**Issue by RGFTheCoder** [JamesPeters98/ChestsPlusPlus#33]
When crafting using items that aren't used up, such as crafting cake, you'd be left with a cake and 3 buckets. The autocrafter only gives the cake, and I really don't want to eat a metal cake XD. Making it output the items should work fine as they could then be filtered by the hoppers.

**Comment by JamesPeters98** [comment]
Ah! Nice find, I think I will output the used items back into the original chest, since that should guarantee there is enough space for it.

**Comment by RGFTheCoder** [comment]
I'd rather it output the items into the output chest/bottom, so we can easily filter them out. Using hoppers for input could cause the system to clog up with iron buckets which would require another system to remove...
