### ISSUE TITLE
Autocrafters Can’t Recognize Non-Vanilla (Custom) Recipes

### ISSUE THREAD

**Issue by Wunga** [JamesPeters98/ChestsPlusPlus#34]
(Originally reported on Discord)

The title pretty much says it all. Autocrafters work great for vanilla recipes, but they don’t* recognize recipes from other plugins. Now, this isn’t a big deal—non-vanilla recipe automation is kind of a fringe feature—but for those who are trying to create tech-based or other unique server concepts, having autocrafters that can process custom recipes would really take Chests++ to the next level. From what I see, there are two major ways to fix this: the devs behind custom crafting plugins can try to register their recipes (I’ve talked to them briefly, and it sounds like this is difficult to achieve without some radical restructuring on their part), or you can try to catch these non-vanilla recipes through some kind of “listening” for a craft event/one of the custom crafting plugins’ craft events.

* Interesting exception: Spigot’s “CrackShot” gun plugin allows custom crafting, and those recipes work out of the box with C++’s autocrafting.

**Comment by RGFTheCoder** [comment]
This plugin does seem to work with datapack custom recipes, possibly, the other plugins should switch to the new datapack recipes, as the majority of the forge community has done (Mod Resources), and this would allow a server owner to disable recipes without disabling the plugin, for troubleshooting.

**Comment by Wunga** [comment]
I’d never tried datapacks with C++ before, but thanks for sharing that it works! Anyway, I wanted to provide a minor update on the autocrafting-custom recipes bug. I’ve switched to a different recipe creator (CraftEnhance by DutchJelly), and now I’ve been successful in adding custom recipes to Chests++’ autocrafters. For reference, the old recipe creator I was using—the one that doesn’t work with C++—is CustomCrafting by WolfyScript. James can close this thread since it’s technically “solved,” but since CustomCrafting is still far more popular (and admittedly more feature-packed) than CraftEnhance, I’d love to see an update that bridges C++ and CustomCrafting. See you around!
