### ISSUE TITLE
PlayerSetupGui for ChestOwner

### ISSUE THREAD

**Issue by ErythroCraft** [JamesPeters98/ChestsPlusPlus#38]
Hi.

Is there a way to create an PlayerGui to enable users/players via sneak right-click to an PlayerSetupGui?

So, I want to create an PlayerSetupGui that should allow an owner of her/his blocks to open an
PlayerSetupGui by sneaking rightClickEvent.

With this Gui she/he can setup members to allow open the protection simplier.

Can you give an update?
Or, you have got an example?

**Comment by JamesPeters98** [comment]
Hi, do you mean something like the Party UI already in the plugin? It's already possible to grant access to your chests using that!

**Comment by ErythroCraft** [comment]
Yep, I've seen. Maybe you can create an Wiki on your page?
