### ISSUE TITLE
Many items not sorting through filter. 

### ISSUE THREAD

**Issue by Any399** [JamesPeters98/ChestsPlusPlus#40]
Using Chests++ 2.4.1, paper 1.16.5. 
 Dark Oak Log, Sandstone Birch planks, spruce planks, nether gold ore, powered rails, sponge, oak button, dark oak door, polished blacktone stair brick, iron trapdoor, dark oak pressure plate, tnt, warped button, birch fence gate, jungle trapdoor, birch boat, minecart with chest, carrot, raw cod, watermelon, iron hoe, netherite hoe, Fortune 3 enchanted book, riptide 3 enchanted book, fire aspect 2 enchanted book, bow, shield, arrow of healing 2, arrow of invisibility (1:00), arrow of slowness (0:30), diamond helmet, golden boots, leather cap, eye of ender, music disc pigstep, popped chorus fruit, fire charge, bone, sugar, book, cyan dye, gunpowder, mundane splash potion, lingering potion of poison posion 2 (0:05), lingering potion of weakness (1:00), lingering potion of water breathing (0:45), lingering potion of invisibility (2:00), lingering potion of swifttness speed 2 (0:22), splash potion of healing, splash potion of regeneration, splash potion of slow falling, splash potion of slowness (1:30), splash potion of leaping jump boost (3:00), potion of poison (1:30), potion of weakness (1:30), splash water bottle, magma cream, glowstone, polished andesite slab, blackstone stairs, brick stairs, polished diorite slab, end stone brick stairs, end stone bricks, granite stairs, stone brick stairs, orange terracotta, magenta terracotta, purple terracotta, polished basalt, clay, block of coal, light gray concrete, orange concrete powder, cyan concrete powder, prismarine stairs, snow block, yellow stained glass, blue stained glass, warped stairs, spruce slab, red sandstone slab, smooth red sandstone, smooth sandstone, smooth stone slab, purpur pillar, purpur stairs, quarts slab, brown wool, yellow wool, light blue wool, blue wool, crimson sign, ender chest, jungle fence, nether brick wall, polished blackstone wall, brown carpet, blue shulker box, magenta shulker box, brown stained glass pane, light blue stained glass pane, blue stained glass pane, light blue carpet, chain, iron bars, birch fence, jungle leaves, spruce sapling, kelp, red mushroom, seagrass, white tulip.)

Sorry for such a long report.. (i went over every item in the game)

**Comment by JamesPeters98** [comment]
What do you mean by not sorting through filter?

**Comment by Any399** [comment]
Hopper with item frame and item in it? I also made a bug report on discord, but no one has replied to it.

**Comment by JamesPeters98** [comment]
Hey, I think you might be using the filters wrong, they all filter correct for me. If you can provide a video or screenshots of what's happening that'd be helpful. Thanks.

**Comment by JamesPeters98** [comment]
Closing as not reproducible
