### ISSUE TITLE
Displays Stay after removal of chest and signs

### ISSUE THREAD

**Issue by idnthvn** [JamesPeters98/ChestsPlusPlus#43]
![2021-03-20_09 21 24](https://user-images.githubusercontent.com/6686550/111870916-c1b8a700-895d-11eb-8ed8-e666b3e7f40f.png)

I just noticed this since last update.
edit: sorry had to crop the image down to one screen

**Comment by JamesPeters98** [comment]
Yeah this sometimes happens after a crash or something similar. If you just reload the plugin they should go away!

**Comment by JamesPeters98** [comment]
If you still have any issues with this reopen and let me know
