### ISSUE TITLE
Paper & Paper Spigot 1.16.5 Java Errors + Crash

### ISSUE THREAD

**Issue by SuperEspresso** [JamesPeters98/ChestsPlusPlus#49]
Crash loop with plugin on clean install with Paper Spigot and Paper. All versions from 1.16.4 upward. 

Image of my console linked below. The following will spam for about 10 minutes, with a massive TPS drop, followed by a server shutdown. 
[https://media.discordapp.net/attachments/625442690603024395/830316800125304903/unknown.png](url)

My server currently runs Spigot 1.16.5, where the plugin runs fine besides autocrafting with more than 1 autocrafter running at a time. We have 4 players on at a time typically, running 6GB on a nVME HDD. The server will give me a bunch of these when more than one autocrafter runs until the server is fully rebooted:

[Mon, 12. Apr 2021 03:52:42 UTC WARN] Can't keep up! Is the server overloaded? Running 7000ms or 140 ticks behind
[Mon, 12. Apr 2021 03:54:24 UTC WARN] Can't keep up! Is the server overloaded? Running 12034ms or 240 ticks behind
[Mon, 12. Apr 2021 03:55:24 UTC WARN] Can't keep up! Is the server overloaded? Running 30272ms or 605 ticks behind
[Mon, 12. Apr 2021 03:55:59 UTC WARN] SuperEspresso moved too quickly! -9.96116643457151,0.0,1.9378005079338578
[Mon, 12. Apr 2021 03:56:25 UTC WARN] Can't keep up! Is the server overloaded? Running 30507ms or 610 ticks behind
[Mon, 12. Apr 2021 03:57:26 UTC WARN] Can't keep up! Is the server overloaded? Running 30884ms or 617 ticks behind
[Mon, 12. Apr 2021 03:57:36 UTC WARN] SuperEspresso moved too quickly! -16.8946241760126,4.703867993957516,6.899825731751704

We have been getting around it by constant restarts. We wanted to move to paper/paper spigot to try and drop TPS and optomize a bit, but it doesn't seem like this is going to work since the plugin crashes the server. We removed all but Chest++ to make sure that is the plugin causing the crash, and it is. 

With a normal load up, the plugin set we have running on a timing report barely registers. It's only Chest++ that does. We turned off all beautification (Armor stands, etc) and turned off hopper moving in unloaded chunks to try and combat the TPS issue. 

Can you recommend anything? Anything at all? We also tried a mob nerfer to make sure that mobs ARE unloading in chunks where a chestlink is in case those boxes are loading the chunk, to make sure that the AI isn't dropping our TPS, which seemed to help a bit-- so now we can use.. 2 to 4 autocrafters at the same time. 

For the record the autocrafters are not from a storage system. They are Box > Crafting table > Hopper > Unlinked chest. They are NOT part of a massive system, but a manual one that is done by hand to ensure there isn't constant items moving through it. There are 12 item frames in the room total. No armor stands.

**Comment by mirkocerati** [comment]
Yep, that's the same exact error I have (see issue #47).
Hope the developer will fix soon!

**Comment by JamesPeters98** [comment]
This is potentially indirectly fixed in 1.17.

**Comment by JamesPeters98** [comment]
This has been fixed and will be in the next release
