### ISSUE TITLE
Possibility of stealing chest with funnel

### ISSUE THREAD

**Issue by brunoyillli** [JamesPeters98/ChestsPlusPlus#5]
Is it possible for a person who doesn't own the chest to drain someone else's chest using a funnel, could you fix this?
Reproduction -
1 - create a chest with protection from one person X
2 - person Y places funnel under person X's chest
3 - person X's chest is drained

**Comment by JamesPeters98** [comment]
Yeah, that's something I can't control maybe use a plugin like WorldGuard or something to control what blocks players can place.

**Comment by brunoyillli** [comment]
good idea, I did it to solve it, but thanks
