### ISSUE TITLE
Display error after removing autocrafting

### ISSUE THREAD

**Issue by SeppDE** [JamesPeters98/ChestsPlusPlus#54]
After removing the autocrafting entry with "/autocrafting remove XXX" and chopping down the worktable afterwards this display error occurs. It can't be fixed with restarting the client or the server. The error itself is visible to other players as well.
![grafik](https://user-images.githubusercontent.com/7773216/125919016-c2dfbdc1-ad55-45fa-b2e9-6ab2cf860493.png)

There is no entry left inside "/autocrafting list" and in the storage.yml is just this one entry with my own UUID:
`  autocraftingtables:
    eee1cfba-f8b1-4621-a5f1-04d1c52d5a37: {}`
    
Tested on the following versions with Release v2.5-Beta-2:
Paper 1.17.1 (#100)
Paper 1.17.1 (#105)
Paper 1.17.1 (#107)

Seems to be the same problem as #43  as well as #25

**Comment by Virologicbody** [comment]
Same issue for me running Paper 1.17.1 (#104)

With one chest I couldn't place a block where the chest was until I restarted the server.

I still have 2 persistent items that remain even after a server restart. I don't really want to use the command to kill armour stands as there are several chests for other players in the area.

![2021-07-27_13 03 48](https://user-images.githubusercontent.com/45987191/127151308-96710b3f-b2b3-4b52-b220-5f53b68b6e6a.png)

**Comment by Virologicbody** [comment]
Although I do have the same issue as the original poster, I have been doing a little testing with chests. I would post on one of the previously mentioned bug reports (#43 & #25) but they are closed.
As all these issues seem to be related I will post here.

I found the items remain if the chests are broken/removed if there are items in the chest. If they are removed/broken while they are empty (sign on them) they remove perfectly with no item. Unfortunately the armour stand still remains even after a server restart.

**Comment by JamesPeters98** [comment]
Taking a look at this now

**Comment by JamesPeters98** [comment]
This will be fixed in the next release!
