### ISSUE TITLE
Repeating Error

### ISSUE THREAD

**Issue by Jmac728** [JamesPeters98/ChestsPlusPlus#59]
![Error on server](https://user-images.githubusercontent.com/96168748/146142533-fb2af089-3761-47d8-8014-9a9362c0c365.PNG)
Currently getting this repeating error after adding Chest++ to my server. I am hosting on Sparked Host. We added it and are just using the hopper sorting. Is there any fix? It get spammed around 5 times per second.

**Comment by JamesPeters98** [comment]
This has been fixed and will be in the next release
