### ISSUE TITLE
Could not pass event Error

### ISSUE THREAD

**Issue by ArticFrowler** [JamesPeters98/ChestsPlusPlus#63]
When running this plugin on a 1.18 server the console log is spammed with tis error.

`INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
26.12 15:00:53 [Server] ERROR Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.5.1-Release
26.12 15:00:53 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null
26.12 15:00:53 [Server] ERROR Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.5.1-Release
26.12 15:00:53 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null
26.12 15:00:54 [Server] ERROR Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.5.1-Release
26.12 15:00:54 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null
26.12 15:00:54 [Server] WARN [ChestsPlusPlus] Task #57 for ChestsPlusPlus v2.5.1-Release generated an exception
26.12 15:00:54 [Server] INFO java.lang.IllegalArgumentException: player must not be null
26.12 15:00:54 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.craftItem(CraftServer.java:1466) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at org.bukkit.Bukkit.craftItem(Bukkit.java:954) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.latest.Crafting.craft(Crafting.java:15) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.crafting.Crafting.craft(Crafting.java:40) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:413) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:263) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder$CraftItems.run(VirtualCraftingHolder.java:226) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
26.12 15:00:54 [Server] WARN [ChestsPlusPlus] Task #58 for ChestsPlusPlus v2.5.1-Release generated an exception
26.12 15:00:54 [Server] INFO java.lang.IllegalArgumentException: player must not be null
26.12 15:00:54 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.craftItem(CraftServer.java:1466) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at org.bukkit.Bukkit.craftItem(Bukkit.java:954) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.latest.Crafting.craft(Crafting.java:15) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.crafting.Crafting.craft(Crafting.java:40) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:413) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder.craftItem(VirtualCraftingHolder.java:263) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at com.jamesdpeters.minecraft.chests.interfaces.VirtualCraftingHolder$CraftItems.run(VirtualCraftingHolder.java:226) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-66]
26.12 15:00:54 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-66]`

**Comment by JamesPeters98** [comment]
Try the latest Beta this should be fixed now!
