### ISSUE TITLE
Old bug back in 1.18.1 (#33) : autocraft eats items that shouldn't be "eaten"

### ISSUE THREAD

**Issue by LilianLem** [JamesPeters98/ChestsPlusPlus#67]
Hello,

I'm running a server on Paper 1.18.1 (build 117) and craft recipes with items consisting of full containers (honey bottles, milk buckets...) are not giving back empty containers in the output.
I saw #33 was already about that a year ago and was fixed, but it seems like something brought it back (or I have another problem on my server).

Crafts I've tested are honey block with 4 honey bottles, and cake with 3 milk buckets.

Could you check if there's something different from other versions' code in your 1.18 files ?

**Comment by JamesPeters98** [comment]
Hey, can you try the latest beta and tell me if that fixes this issue? 

https://github.com/JamesPeters98/ChestsPlusPlus/releases/tag/v2.5.2-Beta-4

**Comment by LilianLem** [comment]
Thanks for the update, but it's still not working 🤔

**Comment by JamesPeters98** [comment]
You may need to delete the auto rafter and set the recipe again maybe 🤔

**Comment by LilianLem** [comment]
My tests were made on an auto crafter made from scratch after the update 😅

**Comment by JamesPeters98** [comment]
This should be fixed in 2.5.2 Beta 5. Let me know!

**Comment by LilianLem** [comment]
It has indeed been fixed, thank you !
